apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-galera-new-pvc
  namespace: mariadb-galera-new
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 40Gi
  storageClassName: managed-nfs-storage
  volumeMode: Filesystem