apiVersion: v1
kind: Secret
metadata:
  name: mariadb-galera-new
  namespace: mariadb-galera-new
type: Opaque
data:
# base64 encoded!
  mariadb-galera-mariabackup-password: Zm9yY2g4MTI3
  mariadb-password: Zm9yY2g4MTI3
  mariadb-root-password: Zm9yY2g4MTI3