replicaCount: 1
existingSecret: mariadb-galera-new
persistence.existingClaim: mariadb-galera-new-pvc
podAntiAffinityPreset: hard
podSecurityContext:
  enabled: false
containerSecurityContext:
  enabled: false
metrics:
  enabled: true